### ISSUE TITLE
Setting the Working Directory

### ISSUE THREAD

**Issue by MasseyRajeev** [Itiviti/gradle-dotnet-plugin#26]
Could not create task ':examples:wsm-vlad:dotnetNugetPush'.
Could not create task of type 'DotnetNugetPushTask'.
Cannot find a valid project file, please setup workingDir / solution correctly

```
dotnet {
    projectName = 'Messenger'

    // where dotnet sdk is installed, default is to use the one specified in PATH
    dotnetExecutable = 'dotnet'

    // the solution / csproj to be built, it will search the workingDir if not specified
    solution = "${projectDir}/src/MicroServices.sln"

    // configuration to be used, default is Release
    configuration = 'Release'

    // Log verbosity of dotnet command
    verbosity = 'Normal'

    // Stop builds if pre-release is detected, can be used when building release build, default is false
    preReleaseCheck = false

    restore {
        // Specifies to not cache packages and HTTP requests.
        noCache = false

        // Forces all dependencies to be resolved even if the last restore was successful. Specifying this flag is the same as deleting the project.assets.json file.
        force = false

        // Delay dotnet restore until dotnetBuild rather than in evaluation phase, could lead to missing project properties due to missing dependencies
        beforeBuild = false
    }

    build {
        // Default values applied
        version = '1.0.3'
        packageVersion = '1.0.3'
    }

    test {
        // filter test to be executed, or use command arguments --dotnet-tests to override (similar to --tests)
        filter = ''

        // test run settings file, no default value
        settings = file(".runsettings")

        // collect code coverage via coverlet, default is true
        collectCoverage = true

        // coverlet output formats, default is opencover
        coverletOutputFormat = 'opencover'

        // [sonar aware] coverlet output path, it must be a directory, default is build/reports/coverlet/
        coverletOutput = file('build/reports/coverlet/')

        nunit {
            // [sonar aware] nunit output path, default is build/reports/nunit/
            testOutputXml = file('build/reports/nunit/')
        }
    }

    nugetPush {
        // Nuget feed url, default is DefaultPushSource in Nuget config if not set
        source = ''
    }
}
```

```
Caused by: org.gradle.api.GradleException: Cannot find a valid project file, please setup workingDir / solution correctly
	at com.itiviti.DotnetPlugin$Companion.parseProjects(DotnetPlugin.kt:58)
	at com.itiviti.DotnetPlugin$Companion.evaluateProject(DotnetPlugin.kt:138)
	at com.itiviti.DotnetPlugin$Companion.access$evaluateProject(DotnetPlugin.kt:28)
	at com.itiviti.DotnetPlugin$apply$extension$1.invoke(DotnetPlugin.kt:152)
	at com.itiviti.DotnetPlugin$apply$extension$1.invoke(DotnetPlugin.kt:27)
	at com.itiviti.extensions.DotnetPluginExtension$allProjects$2.invoke(DotnetPluginExtension.kt:55)
	at com.itiviti.extensions.DotnetPluginExtension$allProjects$2.invoke(DotnetPluginExtension.kt:8)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.itiviti.extensions.DotnetPluginExtension.getAllProjects(DotnetPluginExtension.kt)
	at com.itiviti.extensions.DotnetPluginExtension.getMainProject(DotnetPluginExtension.kt:58)
	at com.itiviti.tasks.DotnetNugetPushTask.<init>(DotnetNugetPushTask.kt:10)
	at com.itiviti.tasks.DotnetNugetPushTask_Decorated.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1969)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:468)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:90)
	... 183 more


```

**Comment by ngyukman** [comment]
Hi, I don't think `solution` support absolute path now, can you set to 'src/MicroServices.sln' ?
